POST http://localhost:6868/api/applications 
Content-Type: application/json

{"name": "APP MOBILE"}

###
GET http://localhost:6868/api/applications 
Content-Type: application/json
app_id: 23045662-1de2-439a-a42b-91e95dd63934

###
GET http://localhost:6868/api/applications/23045662-1de2-439a-a42b-91e95dd63934
Content-Type: application/json

###
DELETE http://localhost:6868/api/applications/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json

###
PUT http://localhost:6868/api/applications/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json

{"name": "TEST"}