POST http://localhost:6868/api/applications 
Content-Type: application/json

{"name": "APP MOBILE"}

###
GET http://localhost:6868/api/applications 
Content-Type: application/json

###
GET http://localhost:6868/api/applications/0acfa118-0ec3-4a0a-8d25-f464cddbeaf8
Content-Type: application/json

###
DELETE http://localhost:6868/api/applications/0acfa118-0ec3-4a0a-8d25-f464cddbeaf8
Content-Type: application/json

###
PUT http://localhost:6868/api/applications/0acfa118-0ec3-4a0a-8d25-f464cddbeaf8
Content-Type: application/json

{"name": "TEST"}