POST http://localhost:6868/api/auth/signup 
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

{
    "firstname": "Teo",
    "lastname": "Lugat",
    "username": "billy",
    "email": "teolugatt@gmail.com",
    "password": "root",
    "birthday": "1991-10-08",
    "adress": "9 rue du progrès",
    "longitude": 48.88039283558442,
    "latitude": 2.4123843153442976,
    "cp": 93310
}

###

POST http://localhost:6868/api/auth/login
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

{
    "emailOrUsername": "teoleboss123",
    "password": "root"
}