POST http://localhost:6868/api/commons/status 
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

{"label": "accept"}

###
GET http://localhost:6868/api/commons/status 
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

###
GET http://localhost:6868/api/commons/status/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

###
DELETE http://localhost:6868/api/commons/status/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

###
PUT http://localhost:6868/api/commons/status/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

{"label": "TEST"}