POST http://localhost:6868/api/commons/status 
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

{"label": "inactive"}

###
GET http://localhost:6868/api/commons/status 
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

###
GET http://localhost:6868/api/commons/status/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

###
DELETE http://localhost:6868/api/commons/status/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

###
PUT http://localhost:6868/api/commons/status/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

{"label": "TEST"}