POST http://localhost:6868/api/terminals 
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

{
    "label": "Terminal 3",
    "longitude": 48.832612927696466,
    "latitude": 2.3252956220567094,
    "address": "39 Rue Gassendi",
    "cp": 75014
}

###
GET http://localhost:6868/api/terminals 
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

###
GET http://localhost:6868/api/terminals/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

###
DELETE http://localhost:6868/api/terminals/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

###
PUT http://localhost:6868/api/terminals/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 7783d5f1-19c1-4b1d-ba0f-3e4887eefb72

{"label": "TEST"}