POST http://localhost:6868/api/terminals 
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

{
    "label": "Terminal 3",
    "longitude": 48.832612927696466,
    "latitude": 2.3252956220567094,
    "address": "39 Rue Gassendi",
    "cp": 75014
}

###
GET http://localhost:6868/api/terminals 
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

###
GET http://localhost:6868/api/terminals/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

###
DELETE http://localhost:6868/api/terminals/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

###
PUT http://localhost:6868/api/terminals/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json
app_id: 0acfa118-0ec3-4a0a-8d25-f464cddbeaf8

{"label": "TEST"}