export const API_ORGANIZATIONS_ROUTES = {
    ORGANIZATIONS: '/organizations',
    ORGANIZATION: (id: string): string => `organizations/${id}`,
    ORGANIZATION_JOBS: (id: string): string => `/organizations/${id}/jobs`,
    ORGANIZATION_MEMBERS: (id: string): string => `/organizations/${id}/members`,
    ORGANIZATION_FAVORITES: (id: string): string => `/organizations/${id}/favorites`,
    ORGANIZATION_CURRENT_SUBSCRIPTION: (id: string): string => `/organizations/${id}/current-subscription`,
    ORGANIZATION_SUBSCRIPTIONS: (id: string): string => `/organizations/${id}/subscriptions`,
    ORGANIZATION_UPDATE_SUBSCRIPTION: (id: string): string => `/organizations/${id}/subscriptions/change`,
    ORGANIZATION_UPDATE_LOGO: (id: string): string => `/organizations/logo/${id}`,
    ORGANIZATION_UPDATE_BANNER: (id: string): string => `/organizations/banner/${id}`,
    ORGANIZATION_UPDATE_MEMBER: (memberId: string): string => `/organizations/member/${memberId}`,
    ORGANIZATION_INVITE: (id: string) => `/organizations/${id}/invite`,
    ORGANIZATION_ANSWER_REQUEST: (memberId: string) => `/organizations/response/${memberId}`,
    REQUEST_ORGANIZATION: (id: string) => `/organizations/${id}/request`,
}