POST http://localhost:6868/api/commons/roles 
Content-Type: application/json

{"label": "TOTORO"}

###
GET http://localhost:6868/api/commons/roles 
Content-Type: application/json

###
DELETE http://localhost:6868/api/commons/roles/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json

###
PUT http://localhost:6868/api/commons/roles/0baccf09-ac85-49a0-a78f-6932b4abea48
Content-Type: application/json

{"label": "ELYAS"}